### PR TITLE
Add a method that updates the reference density

### PR DESCRIPTION
**Pull request by jkpnen**
- [ ] Solve why the reference density does not update when Potku is restarted?
- [ ] Do the tests

### CODE REVIEW

**Comment by jkpnen** [comment]
@tpitkanen , do you have any idea how to keep track on the reference density. At the moment it is defined as the default value (#181) .

**Comment by tpitkanen** [comment]
The per-element `reference_density` is stored in `RecoilElement` (which is saved to a **.sct** or **.rec** file).

The files are actually read by Potku too, even though we concluded that the files are only for use by other programs. `RecoilElement.from_file` is called for each element when opening a request.

**Comment by jkpnen** [comment]
> The per-element `reference_density` is stored in `RecoilElement` (which is saved to a **.sct** or **.rec** file).
> 
> The files are actually read by Potku too, even though we concluded that the files are only for use by other programs. `RecoilElement.from_file` is called for each element when opening a request.
> 
> Edit: and seems like there's no target-wide `reference_density`, so only the element-specific values need to be tracked (in addition to the global default value).

At the moment #234 tracks the reference density i.e. it's updated after restart. What to think of that?

**Comment by tpitkanen** [comment]
> > The per-element `reference_density` is stored in `RecoilElement` (which is saved to a **.sct** or **.rec** file).
> > The files are actually read by Potku too, even though we concluded that the files are only for use by other programs. `RecoilElement.from_file` is called for each element when opening a request.
> > Edit: and seems like there's no target-wide `reference_density`, so only the element-specific values need to be tracked (in addition to the global default value).
> 
> At the moment #234 tracks the reference density i.e. it's updated after restart (on the simulation tab). What to think of that?

Everything must be up-to-date when Potku is running. Restarting should only load the previously serialized values (and re-generate the plots). In other words, a request should be exactly the same before and after a restart (excluding file timestamps etc.).

**Comment by jkpnen** [comment]
> > > The per-element `reference_density` is stored in `RecoilElement` (which is saved to a **.sct** or **.rec** file).
> > > The files are actually read by Potku too, even though we concluded that the files are only for use by other programs. `RecoilElement.from_file` is called for each element when opening a request.
> > > Edit: and seems like there's no target-wide `reference_density`, so only the element-specific values need to be tracked (in addition to the global default value).
> > 
> > 
> > At the moment #234 tracks the reference density i.e. it's updated after restart (on the simulation tab). What to think of that?
> 
> Everything must be up-to-date when Potku is running. Restarting should only load the previously serialized values (and re-generate the plots). In other words, a request should be exactly the same before and after a restart (excluding file timestamps etc.).
> 
> Edit: #236 seems to do this already. Is there something else that needs commenting?

No in this case. But is this PR unnecessary now?

**Comment by tpitkanen** [comment]
> > > > The per-element `reference_density` is stored in `RecoilElement` (which is saved to a **.sct** or **.rec** file).
> > > > The files are actually read by Potku too, even though we concluded that the files are only for use by other programs. `RecoilElement.from_file` is called for each element when opening a request.
> > > > Edit: and seems like there's no target-wide `reference_density`, so only the element-specific values need to be tracked (in addition to the global default value).
> > > 
> > > 
> > > At the moment #234 tracks the reference density i.e. it's updated after restart (on the simulation tab). What to think of that?
> > 
> > 
> > Everything must be up-to-date when Potku is running. Restarting should only load the previously serialized values (and re-generate the plots). In other words, a request should be exactly the same before and after a restart (excluding file timestamps etc.).
> > Edit: #236 seems to do this already. Is there something else that needs commenting?
> 
> No in this case. But is this PR unnecessary now?

Seems like it. I'm reviewing #236 right now, by the way.

**Pull request closed without merging**
